// <auto-generated>
// Code generated by LUISGen LuisForSakuraFirstTry.json -cs Luis.LuisForSakuraFirstTry -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class LuisForSakuraFirstTry: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            Feel_Amused, 
            Feel_Angry, 
            Feel_Anxious, 
            Feel_Bored, 
            Feel_Confident, 
            Feel_Disappointed, 
            Feel_Embarrassed, 
            Feel_Flirty, 
            Feel_Frightened, 
            Feel_Guilty, 
            Feel_Happy, 
            Feel_Hungry, 
            Feel_Insecure, 
            Feel_Jealous, 
            Feel_Sad, 
            Feel_Safe, 
            Feel_Sick, 
            Feel_Stressed, 
            Feel_Thirsty, 
            Feel_Tired, 
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {

            // Built-in entities
            public DateTimeSpec[] datetime;

            public double[] percentage;

            public Temperature[] temperature;

            // Lists
            public string[][] Feel_Type;

            // Instance
            public class _Instance
            {
                public InstanceData[] Feel_Type;
                public InstanceData[] datetime;
                public InstanceData[] percentage;
                public InstanceData[] temperature;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<LuisForSakuraFirstTry>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
